x/emissions/keeper/keeper.go, x/emissions/module/demand.go, x/emissions/module/rewards_calc.go
So that it doesn't accumulate forever
=> Remove met demand after it's been sent as rewards to network actors

x/emissions/module/autocli.go
=> Add brackets to autocli "use" statements

scripts/multinode-local-testnet.sh
I created this script to try to replicate the demo issue locally, I think it will be very useful for future tests.
To access logs of the node after starting with `tmux` you need to run:
1) Open a new terminal
2) Run `tmux attach -t validator1`
=> Script to deploy local multinode testnet

x/emissions/module/autocli.go
Fix autocli message for method updateParams.
=> Fix autocli message for method updateParams

cmd/allorad/cmd/root.go, integration/topic.sh
All the reasoning behind this update is in a comment in this ticket: 
https://linear.app/upshot/issue/ORA-886/add-gasfees-in-the-chain
=> Changing MinGasPrice

x/emissions/keeper/msg_server.go, x/emissions/keeper/msg_server_test.go
Details about this PR in this ticket: 
https://linear.app/upshot/issue/ORA-534/if-stake-was-set-before-node-was-registered-its-existing-stake-isnt
=> Checking existing stake during registration

x/emissions/keeper/query_server.go
Loop var reuses mem addr. 
Fix that making a copy when accum them.
=> Fix bug carrying over pointer from loop

app/api.go, x/emissions/keeper/keeper.go, x/emissions/keeper/msg_server.go, x/emissions/module/autocli.go
Fixes pointer-based issues on loops.
I have reviewed our codebase, should be out of the loop-pointer issue.
=> Loop-Pointer fixes

scripts/l1_node.sh
Links of genesis and peers list to use allora-network gh user content.
=> Update links to allora-network

.github/workflows/release_binary.yml
this builds and publishes `allorad` to the assets of a gitHub release.
=> release binary to github

README.md, docker-compose.yaml, scripts/l1_node.sh
- fix allora-chain docker image to v0.0.7 for testnet
- set default config to testnet instead of edgenet
=> ORA-1029: Fix default config for running a node on testnet + Update README

docker-compose.yaml, x/mint/types/minter.go, x/mint/types/params.go
* lessen extreme inflation
* upgrade version
=> lessen v1 inflation

x/emissions/module/inference_synthesis/forecast_implied_inferences_test.go
=> Correct calc implied inferences

x/emissions/module/inference_synthesis/network_inferences.go, x/emissions/module/inference_synthesis/network_inferences_test.go
Fix `CalcWeightedInference` and test using simulation data
=> Update CalcWeightedInference tests

integration/rewards.sh, x/emissions/keeper/keeper.go, x/emissions/module/rewards/rewards.go
=> Try to get Integration tests at least able to pass

math/dec_test.go
Add tests  for InDelta, SlicesInDelta, SumDecSlice, DecReduce
=> Add Math tests

x/mint/testutil/emissions_keeper_mocks.go
=> Fix broken tests

x/emissions/keeper/inference_synthesis/network_inferences.go
Add inferences and forecast-implied-inferences to the bundle, so they're sent to the reputer in the request.
=> Add inferences + Fore.impl.infs to bundle

Dockerfile, Dockerfile.development
=> Update go version

x/emissions/module/rewards/reputer_rewards.go, x/emissions/module/rewards/rewards.go, x/emissions/module/rewards/rewards_internal.go, x/emissions/module/rewards/scores.go, x/emissions/module/rewards/topic_rewards.go, x/emissions/module/rewards/worker_rewards.go
The EmitRewards function is not intended to panic on errors. This means that the stack trace on errors in EmitRewards stops at the call of EmitRewards and does not adequately help you determine where in the rewards flow an error happened. I used my best judgement to avoid wrapping absolutely every trivial error in e.g. an addition or subtraction, but rather focusing on the function call stack.
This PR uses the cosmos errors.Wrapf function to help track down e.g. consensus errors
it also tweaks some annoying formatting and adds a comment to a function header for a function that lacked a function header comment
=> Wrap errors to give more stack trace-like information

x/emissions/keeper/keeper.go, x/emissions/module/demand.go, x/emissions/module/module_test.go
- fix error on get active topic (it returns wrong value if the number of topicId bigger than `maxTopicPages`)
- fix error on build best price (it was overwritten if the number of requests bigger than `maxRequestPages`)
- fix calculation logic in pagination cursor
=> fix issue on demand

x/emissions/keeper/inference_synthesis/network_regrets.go, x/emissions/keeper/inference_synthesis/network_regrets_test.go
Add one fix so that we don't prematurely calculate self regrets
=> Test regrets

x/emissions/keeper/msgserver/msg_server_registrations.go, x/emissions/keeper/msgserver/msg_server_registrations_test.go
Test reputer and worker unregistration
Fix bug that did not allow unregistering reputers
=> Test and fix unregister

x/emissions/module/rewards/reputer_rewards.go, x/emissions/module/rewards/rewards.go, x/emissions/module/rewards/rewards_internal.go, x/emissions/module/rewards/rewards_internal_test.go, x/emissions/module/rewards/rewards_test.go, x/emissions/module/rewards/worker_rewards.go
Delegator rewards should be handled separately by Michael's logic in https://github.com/allora-network/allora-chain/pull/194/ so we just need to handle reputer rewards correctly in this pr
=> Increase stake for reputer rewards

x/emissions/keeper/msgserver/msg_server_requests_test.go
topics with more met demand get more reward
=> Test Invariant: topics with met more demand get more reward

x/emissions/keeper/msgserver/msg_server_losses.go, x/emissions/keeper/msgserver/msg_server_stake_test.go, x/emissions/module/rewards/reputer_rewards.go, x/emissions/module/rewards/reputer_rewards_test.go, x/emissions/module/rewards/rewards.go
Migrate Score calculation from InsertBulkReputerPayload to reward section
Reference [ORA-1342](https://linear.app/upshot/issue/ORA-1342/migrate-score-calculation-to-reward-section)
=> [ORA-1342] migrate score calculation to reward

integration/create_topic_test.go
New loss function on integration tests
=> New loss fn with correct block height passing

go.mod, go.sum, math/dec.go, math/dec_test.go
Considering that Cosmos SDK will be using it soon, we decided to update the cockroach `apd` version
Ticket: https://linear.app/upshot/issue/ORA-1353/should-we-upgrade-to-apd-v3
=> Update apd to v3

Makefile
- Added build tags processing to enable ledger support
Ticket: https://linear.app/upshot/issue/ORA-1122/add-ledger-support
=> Added ledger support

x/emissions/keeper/inference_synthesis/network_regrets_test.go, x/emissions/module/rewards/rewards_test.go, x/emissions/module/rewards/scores_test.go
- Add comments to clarify complex relationship tests
- Simplify the setup of a couple of tests
=> Add test explanations and simplify setup

app/api.go, stress/n_workers_reputers__stress_test.go, stress/stress_test.go
* Use WaitGroup for the subroutines and give an end to the process
* Change waiting time (no need to wait if elapsed time is bigger than an epoch)
* env vars defined as function parameters
=> Add WaitGroup, env vars and others

test/local_testnet_l1.sh, test/stress/n_workers_reputers__stress_test.go, test/stress/stress_test.go
This is not a strict test because some of the newly created accounts haven't had a chance to acquire rewards in some cases, either due to no contributing enough or not having a chance to be present during a round where there was not a nonce error
=> ORA1471 Check that worker balance and reputer stake increases during stress testing

math/utils_test.go, x/emissions/keeper/inference_synthesis/network_inferences.go, x/emissions/keeper/inference_synthesis/network_inferences_test.go
Split out into a new diff so most recent changes can be easily viewed
=> ORA1528 Finish Guilhermes work on adding Diederiks changes (2/2)

x/emissions/keeper/inference_synthesis/forecast_implied_inferences.go, x/emissions/keeper/inference_synthesis/forecast_implied_inferences_test.go, x/emissions/keeper/inference_synthesis/network_inferences.go, x/emissions/keeper/inference_synthesis/network_inferences_test.go
Simplify the logic of adding Diederik's changes to the codebase. Remove failing tests to unblock edgenet, I will fix them next week.
=> ORA1532 Rework adding diederiks math changes to the codebase

x/emissions/keeper/inference_synthesis/synth_palette_forecast_implied_test.go
As PNorm is increased, we see increased spread in the weights that are calculated per regret
=> ORA1241 Increasing PNorm increases spread of regrets

x/emissions/keeper/inference_synthesis/synth_palette_weight.go
Add coverage against unexpected nil pointer dereferences.
It will throw error in that case.
Note: This is a very conservative take here, sending error if there is any - thus sending no weights; another option could be to ignore those that are nil but still return the completed ones, if any. But I'm unsure of the consequences, so rather return error and handle as such.
=> Add nil dereference coverage and error control

x/emissions/module/rewards/worker_rewards.go
Make some changes to ForecastingUtility for clarity
=> ORA1709 Updates to ForecastingUtility

test/local_testnet_l1.sh, x/emissions/module/rewards/worker_rewards.go
if sum_j denom==0 => use abs(T_i) as denom instead
and if also abs(T_i)==0 => maximise
=> Update forecast utility function

Makefile, scripts/init.sh, test/stress/workers_test.go, x/emissions/keeper/inference_synthesis/network_inference_builder.go, x/emissions/keeper/inference_synthesis/network_inferences.go, x/emissions/keeper/inference_synthesis/synth_palette_weight.go
- Fix error handling in GetLatestNetworkInferences
...
=> v2 testnet bugfixes

x/emissions/keeper/inference_synthesis/network_inference_builder.go, x/emissions/keeper/inference_synthesis/network_regrets.go, x/emissions/keeper/inference_synthesis/synth_palette_factory.go, x/emissions/keeper/keeper_test.go, x/emissions/module/rewards/rewards_test.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> ORA1811 Help redesign new participants edge cases

app/topics_handler.go, x/emissions/keeper/msgserver/msg_server_losses.go, x/emissions/keeper/msgserver/msg_server_losses_test.go, x/emissions/keeper/msgserver/msg_server_worker_payload.go, x/emissions/keeper/msgserver/msg_server_worker_payload_test.go, x/emissions/types/errors.go
Fix a misleading error message.
Tests have been modified.
- [X ] N/A
=> Misleading error message + remove nonsensical gt_lag usage

.gitignore, README.md, docker-compose.yaml, scripts/head.sh, scripts/l1_node.sh
Closes: ORA-1830
*(or)*
*(or)*
*(example:)*
=> Add heads iac

docker-compose.yaml
Closes: #XXX
> updated the allora-chain docker version for the docker-compose used by NOps
- *Manually verified the change by  running `docker-compose up`*
=> hotfix to bump up docker version for nops

README.md, docker-compose.yaml, scripts/l1_node.sh
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> Add statesync option

math/utils_test.go, x/emissions/keeper/keeper.go, x/emissions/module/rewards/topic_rewards.go
Closes: #ORA-1841 
Fix iteration causing decay rate being applied multiple times
This change is a small change that reuses same unit tests.
- [X ] N/A - It is a bugfix.
=> Fix decay rate issue - multiple dripping calls

x/emissions/keeper/msgserver/msg_server_worker_payload.go, x/emissions/keeper/msgserver/msg_server_worker_payload_test.go
Check if inference is not new in msg server
*(or)*
*(or)*
*(example:)*
=> [ORA-1918] Fix inference not nil check

x/emissions/keeper/keeper.go, x/emissions/module/abci.go
Added error handling to avoid potential inconsistent state if this function fails
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> [ORA-1901] Added error handling and logs in reset churnable topics

.gitignore, test/ibc/relayer/.env, test/ibc/relayer/Makefile, test/ibc/relayer/configs/allora.json, test/ibc/relayer/configs/osmosis.json, test/ibc/relayer/docker-compose.yml, test/ibc/relayer/paths/demo.json, test/ibc/relayer/run-relayer.sh, test/ibc/relayer/scripts/setup_allora.sh, test/ibc/relayer/scripts/setup_osmosis.sh
Test IBC module for sending/receiving to another chain. At this testing we used osmosis for target chain.
This change includes some testing scripts and build configuration for testing environment.
=> Add testing script for working with osmosis

x/ibc/gmp/ibc_middleware.go
Add processing logic to handle messages coming from unexpected nodes.
*(or)*
*(or)*
*(example:)*
=> Add error message handling

x/emissions/keeper/actor_utils/losses.go, x/emissions/keeper/actor_utils/worker.go, x/emissions/keeper/inference_synthesis/network_inferences.go, x/emissions/keeper/keeper.go
Fix having no forecasts, nonce must be closed anyway
This change is covered by related tests
=> fix having no forecasts, using empty

docker-compose.yaml, scripts/l1_node.sh
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> Workaround to have the only config dir 

x/emissions/migrations/v1_to_v2.go, x/emissions/migrations/v1_to_v2_test.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> Migration tests

x/emissions/api/v2/query.pulsar.go, x/emissions/api/v2/query_grpc.pb.go, x/emissions/keeper/queryserver/query_server_inferences.go, x/emissions/keeper/queryserver/query_server_inferences_test.go, x/emissions/module/autocli.go, x/emissions/proto/emissions/v2/query.proto, x/emissions/types/query.pb.go, x/emissions/types/query.pb.gw.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> Add queries for new regrets

x/emissions/keeper/genesis.go, x/emissions/keeper/keeper.go, x/emissions/module/abci.go, x/emissions/module/rewards/rewards_internal.go, x/emissions/module/stake_removals.go
https://github.com/sherlock-audit/2024-06-allora-judging/issues/104
https://github.com/sherlock-audit/2024-06-allora-judging/issues/84
https://github.com/sherlock-audit/2024-06-allora-judging/issues/24 (partially, most of the issues pointed out here are already solved by other PRs)
https://github.com/sherlock-audit/2024-06-allora-judging/issues/92
https://github.com/sherlock-audit/2024-06-allora-judging/issues/93
Also added in a improvement in the queries GetForecastScoresUntilBlock and GetInferenceScoresUntilBlock
=> [PROTO-2094] Remaining confirmed issues on sherlock audit

x/mint/module/autocli.go
* Expose the UpdateParams method to the x/mint autocli
* Allows whitelisted agents to adjust x/mint params
* Manually tested
* Use correct mint module version and ensure the upgrade still runs @relyt29
=> [PROTO-2136] Add mint update-params autocli call

CHANGELOG.md, test/integration/worker_inference_and_forecast_test.go, test/stress/README.md, test/stress/n_workers_reputers_stress_test.go, test/stress/reputers_test.go, test/stress/stress_test.go, test/stress/workers_test.go, x/emissions/keeper/actor_utils/losses.go, x/emissions/keeper/msgserver/msg_server_worker_payload_test.go, x/emissions/proto/emissions/v2/worker.proto
Align code (names, comments, etc) to the single insertion txs. 
Tested by running tests and especially stress tests. 
No additional docs needed due to being an adaptation to other code.
=> Remove bulk and leader concepts from code

CHANGELOG.md, README.md, app/export.go, math/dec.go
Hello
I fixed several typos found in your docs.
Br, Elias.
=> docs: fix spelling issues

x/emissions/module/rewards/rewards.go, x/emissions/module/rewards/rewards_internal_test.go, x/emissions/module/rewards/worker_rewards.go, x/emissions/module/rewards/worker_rewards_test.go
Added missing update to the forecaster score ratio
=> Updating forecaster score ratio

CHANGELOG.md, x/emissions/keeper/keeper.go, x/emissions/keeper/msgserver/msg_server_reputer_payload.go, x/emissions/keeper/msgserver/msg_server_reputer_payload_test.go
* Fix - close reputer window on the upper part
* Add 4 tests to strictly define reputer window
* Add basic validation on appending reputer losses
PROTO-2246
=> fix reputer window + strict reputer window tests + lint

scripts/upgrade.sh
Script to automate the creation of upgrade proposals
https://linear.app/alloralabs/issue/PROTO-2267/create-a-script-to-automate-the-creation-of-upgrade-proposals
Yes. Manually tested locally.
=> Script to automate the creation of upgrade proposals

x/emissions/keeper/keeper.go, x/emissions/keeper/keeper_test.go, x/emissions/module/rewards/topic_rewards_test.go
Fixes hyper aggressive topic dripping
Adds a test, fixes another test that was not setting the `BlocksPerEpoch` on the params, getting a div by zero.
=> Quo vs Mul to apply dripping

x/emissions/keeper/actor_utils/losses_test.go, x/emissions/keeper/keeper.go, x/emissions/keeper/keeper_test.go, x/emissions/module/rewards/topic_rewards_test.go
=> Release v0.4.0 2 dev

x/emissions/module/rewards/rewards_test.go, x/emissions/module/rewards/scores_test.go
Fixes on the reward_test failing
=> WIP Test fixes for rewards_test - one test failing

scripts/coverage.sh, scripts/upgrade.sh
Change upgrade.sh to use minutes; exclude generated files from coverage
=> Change upgrade.sh to use minutes; exclude generated files from coverage

x/emissions/migrations/v4/migrate.go, x/emissions/migrations/v4/migrate_test.go, x/emissions/module/module.go
- New migration to fix the incomplete v3 emissions module migration
=> Add emissions v4 migration

CHANGELOG.md, x/emissions/types/msg_create_topic.go
Validate new fields in topic creation.
=> New topic field validations

x/emissions/keeper/msgserver/msg_server_topics.go, x/emissions/migrations/v4/migrate.go, x/emissions/types/msg_create_topic.go
make the migration more careful, make the creation of topics have a check on new values
=> migration to be more careful, create topic validations

.golangci.yml
Expand gosec linter lexicon to include crypto-native words
=> Expand gosec linter lexicon to include crypto-native words

CHANGELOG.md, math/utils.go
Protect EMA against previous or incoming `NaN` values.
PROTO-2302
=> EMA: NaN protection

test/invariant/inferences_test.go, test/invariant/transitions_test.go, test/local_testnet_l1.sh
- Fixing context usage in invariant tests
=> Fix invariant tests

x/emissions/keeper/actor_utils/losses.go, x/emissions/keeper/keeper.go, x/emissions/keeper/keeper_test.go, x/emissions/keeper/msgserver/msg_server_demand.go, x/emissions/keeper/msgserver/msg_server_params.go, x/emissions/keeper/msgserver/msg_server_registrations.go, x/emissions/keeper/msgserver/msg_server_reputer_payload.go, x/emissions/keeper/msgserver/msg_server_stake.go, x/emissions/keeper/msgserver/msg_server_stake_test.go, x/emissions/keeper/msgserver/msg_server_topics.go, x/emissions/keeper/msgserver/msg_server_whitelist.go, x/emissions/keeper/msgserver/msg_server_worker_payload.go, x/emissions/module/abci.go, x/emissions/module/rewards/rewards.go, x/emissions/types/validations.go
- After reviewing all the msgs, I saw some missing validations. I will address this in this PR
- Also saw some opportunities to do a small refactoring to avoid duplicate queries
=> Added missing validation in data ingress and refactoring

CHANGELOG.md, go.mod, x/emissions/keeper/msgserver/msg_server_demand.go, x/emissions/keeper/msgserver/msg_server_params.go, x/emissions/keeper/msgserver/msg_server_registrations.go, x/emissions/keeper/msgserver/msg_server_reputer_payload.go, x/emissions/keeper/msgserver/msg_server_stake.go, x/emissions/keeper/msgserver/msg_server_topics.go, x/emissions/keeper/msgserver/msg_server_whitelist.go, x/emissions/keeper/msgserver/msg_server_worker_payload.go, x/emissions/keeper/queryserver/query_server_forecasts.go, x/emissions/keeper/queryserver/query_server_inferences.go, x/emissions/keeper/queryserver/query_server_losses.go, x/emissions/keeper/queryserver/query_server_params.go, x/emissions/keeper/queryserver/query_server_registrations.go, x/emissions/keeper/queryserver/query_server_reward.go, x/emissions/keeper/queryserver/query_server_score.go, x/emissions/keeper/queryserver/query_server_stake.go, x/emissions/keeper/queryserver/query_server_topics.go, x/emissions/keeper/queryserver/query_server_whitelist.go, x/emissions/metrics/labels.go, x/emissions/metrics/metrics_util.go, x/emissions/module/rewards/topic_rewards.go, x/emissions/types/events.go
Add counter, gauges metrics using telemetry  on every query/txs
=> Add metrics on tx/query

.gitignore, cmd/allorad/cmd/commands.go, cmd/allorad/cmd/testnet.go, test/generate_genesis.sh, test/integration/integration_test.go, test/invariant/invariant_test.go, test/local_testnet_l1.sh, test/local_testnet_upgrade_l1.sh, test/stress/README.md, test/stress/stress_test.go
Port in-place-testnet implementation to current version on main (v0.5.0) so we can use it to test the upgrade to version v0.6.0.
Cherry picked from this PR: https://github.com/allora-network/allora-chain/pull/612
https://linear.app/alloralabs/issue/PROTO-2668/implement-in-place-testnet-on-version-v050
Tested using: https://www.notion.so/upshothq/Testing-upgrades-locally-or-on-devnet-11f34d40db4880abac30d507ed4ee2a6
=> Implement in-place-testnet on version v0.5.0

CHANGELOG.md, utils/migutils/migutils.go, utils/migutils/migutils_test.go, x/emissions/migrations/v3/migrate.go, x/emissions/migrations/v3/migrate_test.go, x/emissions/migrations/v4/migrate.go, x/emissions/migrations/v5/migrate.go, x/emissions/migrations/v5/migrate_test.go
This is a patch, but still part of v0.6.0 release.
We were not deleting enough values in the KV store that may have been affected by initial regret poisoning. This had to be corrected or else other values would risk re-poisoning everything else within each topic.
- Re-uses existing function + unit test
- Was original intention of original author of that migration. Documented through comments.
=> Wipe all values
