allora-network/allora-chain

x/emissions/module/autocli.go

#34 and various other PRs have added a number of new transaction types to the tx.proto and RPC exposed by a node. This PR updates the autocli.go file to ensure that the node CLI tool can send every type of transaction that nodes support.

Update Autocli to support all RPC Methods

---

app/topics_handler.go
x/emissions/module/demand.go

* The go loop nature uses the same address on the iterator. So the value (instead of the ref) needs to be used, otherwise all go subroutines on iterations will use the same addr (that of the last element).
* Also happening on demand calcs.
This was causing that too many requests for a topic were made, and that other topics got none.

Fix overwriting topics on calls and demand

---

app/app.go

Issue with validator power reduction causing an over flow, with 10^18, we halted.
After researching, looks like it is an issue with the validator power reduction calculations, causing an overflow in CometBFT. 
Discussion
https://github.com/cosmos/cosmos-sdk/issues/8357
Sifchain, BNB Greenfield, Ethermint all 10^18
https://github.com/search?q=NewIntFromBigInt%28new%28big.Int%29.Exp%28big.NewInt%2810%29%2C+big.NewInt%2818%29%2C+nil%29%29&type=code

changes default power reduction to 10^18

---

x/emissions/module/inference_synthesis/forecast_implied_inferences.go
x/emissions/module/inference_synthesis/forecast_implied_inferences_test.go
x/emissions/module/inference_synthesis/network_losses_test.go

I found a couple of bugs in the implementation of `CalcForcastImpliedInferences`. Fix those bugs. Note that only the first test passes currently, the other two are pending a resolution of a dispute over what the correct output value should be for the equation. Diederik should be able to give final confirmation tomorrow morning.

Fix ea 3-8 implementation and unit test

---

.gitignore
scripts/coverage.sh
x/emissions/keeper/msgserver/msg_server_losses_test.go
x/emissions/keeper/msgserver/msg_server_registrations_test.go
x/emissions/keeper/msgserver/msg_server_requests_test.go

Create a new test coverage tool that displays data in an easy-to-parse format (lcov.info). lcov.info is not native to go. The native go coverage viewer is not good. An external tool is used to convert the go coverage file to lcov to enable better display: `gcov2lcov` which can be installed with 
`go install github.com/jandelgado/gcov2lcov@latest`
I had to comment out a bunch of failing tests, next step is to get those tests back online. 
After removing generated files and libraries, we sit at about 26% test coverage (!!!)

Test coverage viewer

---

app/topics_handler.go
x/emissions/keeper/inference_synthesis/network_inferences.go
x/emissions/keeper/inference_synthesis/network_inferences_test.go
x/emissions/keeper/keeper.go
x/emissions/keeper/msgserver/msg_server_losses.go
x/emissions/module/abci.go

* CalcNetworkInferences to still return incomplete set if any of the calculations for ValueBundle components have an error, providing empty arrays instead (affects OneIn/Out mostly)
* Chain to make a request to reputers with incomplete ValueBundles if that's the case 
* Ensure requests to workers and reputer are made correctly 
* workers block height `t`, reputers blocks `(t - EpochLength, t - 2*EpochLength)`, checking against subzero heights.
* Added two CalcNetworkInferences tests.
* Incomplete data to still return data. 
* **Here's a catch**: currently if no regrets are set, the `CalcOneInForecasterValues` fails bc regrets are no higher 
than epsilon, thus having to use empty array. Is that the correct behaviour, or do we want to change the behaviour inside `CalcOneInForecasterValues` …

Make reputer request be made if incomplete data

---

x/emissions/module/rewards/reputer_rewards_test.go
x/emissions/module/rewards/rewards.go
x/emissions/module/rewards/rewards_test.go
x/emissions/module/rewards/scores_test.go

Added 2 tests:
On the participants' rewards distribution level: If more reputers have the same totalReputerRewards to share, there will be fewer rewards for each reputers.
On the task rewards distribution level: If there are more reputers, a higher share of the total rewards will be allocated to reputers.

Added tests for reward distribution between participants and tasks

---

x/emissions/keeper/keeper.go
x/emissions/keeper/keeper_test.go

- GetParamsEpsilon
- GetParamsTopicCreationFee
- GetParamsRegistrationFee
- GetWorkerLatestInferenceByTopicId
- GetReputerByLibp2pKey
- GetTopic
- PopChurnReadyTopic
- AddChurnReadyTopic
- CalcAppropriatePaginationForUint64Cursor

[ORA-1292] Additional keeper tests

---

x/mint/keeper/emissions.go
x/mint/keeper/emissions_test.go
x/mint/keeper/keeper.go
x/mint/keeper/keeper_test.go
x/mint/module/abci.go
x/mint/module/module_test.go
x/mint/testutil/expected_keepers_mocks.go
x/mint/types/expected_keepers.go

* Fixes bug where we were calling `StakingTokenSupply` instead of `TotalBondedTokens` thinking that the former was the supply of tokens staked when in reality it's just the total supply of uAllo and we need to get TotalBondedTokens to get the number of staked tokens
* Adds a test to show that the target emission per unit stake goes down when the number of tokens staked goes up, but that the total inflation rate continues to go up because the total amount of tokens staked went up.

[ORA-1313] Fix Staking Supply Bonded Tokens Bug, Add tests for relationship between inflation rate and higher rate of staking

---

x/emissions/keeper/keeper.go
x/emissions/keeper/msgserver/msg_server_worker_payload.go
x/emissions/module/rewards/reputer_rewards.go
x/emissions/module/rewards/rewards.go
x/emissions/module/rewards/rewards_internal.go
x/emissions/module/rewards/rewards_test.go
x/emissions/module/rewards/worker_rewards.go

- Covering single participant's edge cases in the rewards flow.
- Refactoring some functions in rewards.go.
- Fixes and optimizations.
PS: This PR is just focused on covering these edge cases in the rewards flow. It will need additional testing to cover single participant's edge cases in the network inference part (`network_inferences.go`).
Ticket: https://linear.app/upshot/issue/ORA-1321/rewards-number-ratio-invalid-slice-length-consensus-failure

[ORA-1321] Covering single participants edge cases in rewards flow

---

integration/inference_request_test.go
integration/staking_test.go
x/emissions/keeper/msgserver/msg_server_topics.go
x/emissions/keeper/msgserver/msg_server_topics_test.go

Remove activation from topic creation. 
Moved activation check after reputer staking.
Tested on chain writing with 1 worker and 1 reputer.

Remove auto-activation on topic creation

---

app/topics_handler.go
x/emissions/keeper/inference_synthesis/network_inferences.go
x/emissions/keeper/msgserver/msg_server_losses.go
x/emissions/keeper/msgserver/msg_server_losses_test.go
x/emissions/module/rewards/rewards.go
x/emissions/module/rewards/rewards_test.go
x/emissions/module/rewards/scores.go
x/emissions/module/rewards/worker_rewards.go
x/emissions/module/rewards/worker_rewards_test.go

- In network inference calc: 
If 0 inference: throw error
If 1 inference: network inference == single inference
if  >1 inference: calc network inference
- In network loss calc: 
If 0 forecasts: continue calc
If 1 inference: no need for to reputer to send one-out loss
- In scores calc :
If 1 forecast or inferer: score will be zero
In the case of scores, I needed to add code to handle when one-out losses are not empty (which will happen when we have single participant cases). Previously, we were generating random one-out losses for single participant cases in our tests and we were considering them; now we just do not consider one-out/one-in losses in these cases and use zero as score.
Reference: https://linear.app/upshot/issue/ORA-1374/consensus-failure-rewards-number-ratio-invalid-slice-len …

Covering edge cases in Network Inference calc

---

app/topics_handler.go
x/emissions/keeper/keeper.go
x/emissions/keeper/keeper_test.go
x/emissions/module/abci.go

- Removing stateful changes from topic handler
Ticket:  https://linear.app/upshot/issue/ORA-1421/move-churnreadytopics-removal-to-outside-topic-handler

ORA1421 - Changed churn ready topic usage

---

stress/chain/node_config.go

The stress tests were running out of gas, set the gas amount to auto and then add a multiplier of +20% so we can be sure we don't have out of gas issues
Tested by adding the following line to log info about successful transactions, seeing that transactions are successful with over 300k gas, and that there is a reasonable buffer between `GasWanted` and `GasUsed`
`fmt.Printf("tx response for broadcasting worker, err %v, gasUsed %v, gasWanted %v", err, txResp.GasUsed, txResp.GasWanted)`

Unlimit gas in Stress Test by setting limit auto

---

x/emissions/module/rewards/rewards.go

I checked the ordering of the flows, `GetAndOptionallyUpdateActiveTopicWeights` is called before `EmitRewards`, which is what does the resets (and is changed in this diff)

[ORA-1445] Only reset topic fee revenue counter if topic is "top" topic being paid out rewards to

---

x/emissions/keeper/inference_synthesis/network_losses.go
x/emissions/keeper/inference_synthesis/network_losses_test.go

- Fallback stake-weighted combined loss to `epsilon` if it's equal to zero
Ticket: https://linear.app/upshot/issue/ORA-1391/no-weights-in-one-reputerlosses-breaks-the-calcnetworklosses

Fix edge case zero combined loss

---

x/emissions/keeper/keeper.go
x/emissions/keeper/msgserver/msg_server_params.go
x/emissions/keeper/msgserver/msg_server_whitelist.go
x/emissions/keeper/queryserver/query_server_registrations.go
x/emissions/keeper/queryserver/query_server_stake.go
x/emissions/keeper/queryserver/query_server_stake_test.go
x/emissions/keeper/queryserver/query_server_whitelist.go

Adds validation for strings in all ingresses (msg and query server) that should be bech32.
Tests fixed in https://github.com/allora-network/allora-chain/pull/275

validate bech32 strings on ingresses

---

x/emissions/keeper/inference_synthesis/network_losses.go
x/emissions/module/rewards/reputer_rewards_test.go
x/emissions/module/rewards/rewards_internal.go
x/emissions/module/rewards/rewards_internal_test.go
x/emissions/module/rewards/scores.go
x/emissions/module/rewards/worker_rewards.go

-> Covering edge cases where:
1) All reported inferer values are 0
2) All reported forecaster values are 0
...
Considering all properties of the Reputer Value Bundle. 
-> Critical fix where we start using the fTolerance from the topic instead of a mocked one. 
Ticket: https://linear.app/upshot/issue/ORA-1453/cover-edge-case-zero-values-in-all-reported-losses-values

Covering edge cases for zero values in all reported losses

---

x/emissions/keeper/genesis.go
x/emissions/keeper/inference_synthesis/inference_synthesis_test.go
x/emissions/keeper/msgserver/msg_server_demand.go
x/emissions/keeper/msgserver/msg_server_test.go
x/emissions/keeper/msgserver/msg_server_worker_payload.go
x/emissions/keeper/queryserver/query_server_test.go
x/emissions/module/module_test.go
x/emissions/module/rewards/rewards.go
x/emissions/module/rewards/rewards_test.go
x/emissions/types/keys.go
x/mint/module/module_test.go

Removes the alloraRequests module account, and sends payments directly to the ecosystem bucket instead.
Built off of @kpeluso's work in and closes #276 however that PR was built against a different PR that hasn't yet been merged and might be superseded by @guilherme-brandao's work. So this PR is a git diff patch applied against major-upgrade and with the tests and compiler errors fixed.

[ORA-1456] [ORA-1449] Remove AlloraRequests Module Account

---

app/api.go
app/topics_handler.go
test/stress/README.md
x/emissions/keeper/inference_synthesis/forecast_implied_inferences.go
x/emissions/keeper/inference_synthesis/network_inferences.go
x/emissions/keeper/inference_synthesis/network_losses.go
x/emissions/keeper/inference_synthesis/network_regrets.go
x/emissions/keeper/keeper.go
x/emissions/keeper/msgserver/msg_server_losses.go
x/emissions/keeper/msgserver/msg_server_worker_payload.go
x/emissions/keeper/topic_weight.go
x/emissions/module/abci.go
x/emissions/module/module.go
x/emissions/module/rewards/rewards.go
x/emissions/module/rewards/topic_rewards.go
x/emissions/types/msg_insert_bulk_reputer_payload.go
x/mint/keeper/emissions_test.go

• Stop using `fmt.Print` for general logs and use `ctx.Logger` with `Debug` or `Info` depending on the purpose.
• Remove redundant logs and some logs that apparently is not useful anymore.
Adapt the error log pattern:
• For msg-related errors: use `Wrapf ` to return a meaningful message to the user.
• For validator processing errors: use `ctx.Logger` - use `Warn` for non-throwing errors, otherwise use `Error`.
Ticket: https://linear.app/upshot/issue/ORA-1413/println-log

[ORA-1413] Remove fmt.Print statements

---

x/emissions/module/autocli.go

Fix duplicated name of functions, set up some convention on related staking delegation functions.
(`reputer-topic-stake` was duplicated)

Fix duplicated name of query

---

x/emissions/keeper/inference_synthesis/network_inferences_test.go
x/emissions/keeper/inference_synthesis/synth_palette_bootstrap.go
x/emissions/keeper/inference_synthesis/synth_palette_factory.go
x/emissions/keeper/inference_synthesis/synth_palette_forecast_implied_test.go
x/emissions/keeper/inference_synthesis/synth_palette_weight.go
x/emissions/keeper/inference_synthesis/types.go

Consider the edge cases:
- If all inferers are new, ignore the forecasters, and set the weights of all inferers to 1, irrespectively of the number of not-new forecasters.
- If one inferer is not new and all other inferers are new, set the weight of the not-new inferer to 1, and all others (including the forecasters, because we don’t need them anyway in this case) get a zero weight.
- If >1 inferer is not new, calculate weight as in the paper for all not-new workers (inferer and forecaster), and don’t include any new workers in the regret calculation.

Cover regrets/weights new participants edge cases

---

app/api.go
app/topics_handler.go
scripts/l1_node.sh
x/emissions/keeper/inference_synthesis/common.go
x/emissions/keeper/inference_synthesis/network_inference_builder.go
x/emissions/keeper/inference_synthesis/network_inferences.go
x/emissions/keeper/inference_synthesis/synth_palette_bootstrap.go
x/emissions/keeper/inference_synthesis/synth_palette_factory.go
x/emissions/keeper/inference_synthesis/synth_palette_forecast_implied.go
x/emissions/keeper/inference_synthesis/synth_palette_forecast_implied_test.go
x/emissions/keeper/inference_synthesis/types.go
x/emissions/module/rewards/rewards.go
x/emissions/module/rewards/topic_rewards.go
x/emissions/module/rewards/topic_skimming.go

Added context specific wrapped loggers for better logs.
When initializing the chain we can now set the log level of specific processes like `rewards`, `inference_synthesis` and `topic_handler`.
To do this, the chain needs to be initialized like this: 
```
allorad start --log_level "*:error,state:info,server:info,rewards:debug,inference_synthesis:debug,topic_handler:debug"
```
Ticket: https://linear.app/upshot/issue/ORA-1602/improve-logs-for-inference-synthesis-and-rewards

Added context specific wrapped loggers

---

x/emissions/api/v1/stake.pulsar.go
x/emissions/keeper/keeper.go
x/emissions/keeper/keeper_test.go
x/emissions/keeper/msgserver/msg_server_demand_test.go
x/emissions/keeper/msgserver/msg_server_losses_test.go
x/emissions/keeper/msgserver/msg_server_params_test.go
x/emissions/keeper/msgserver/msg_server_registrations_test.go
x/emissions/keeper/msgserver/msg_server_stake.go
x/emissions/keeper/msgserver/msg_server_stake_test.go
x/emissions/keeper/msgserver/msg_server_test.go
x/emissions/keeper/msgserver/msg_server_topics_test.go
x/emissions/keeper/msgserver/msg_server_whitelist_test.go
x/emissions/keeper/msgserver/msg_server_worker_payload_test.go
x/emissions/proto/emissions/v1/stake.proto
x/emissions/types/stake.pb.go

This prevents an attacker from being able to withdraw stake multiple times after waiting the delay period once.

[ORA-1620] Clear data from stake removal queue after a ConfirmStakeRemoval call is completed

---

x/emissions/keeper/inference_synthesis/network_inferences.go
x/emissions/keeper/inference_synthesis/network_inferences_test.go
x/emissions/keeper/keeper.go
x/emissions/keeper/keeper_test.go
x/emissions/keeper/queryserver/query_server_inferences.go

- GetLastNetworkInference was using EpochLastEnded as a reference to query the network inference, which is not optimal since this property is updated before the worker sends the inferences.
- Getting the last inferences reported and its `blockHeight` -> then getting the topic `EpochLength` -> `blockHeight - EpochLength` should get the losses from the previous time step. If it exists, calculate and return the network inference.
Ticket: https://linear.app/upshot/issue/ORA-1666/debug-getlatestnetworkinference-returning-empty-values-on-edgenet

[ORA-1666] Fix get last network inference query

---

x/emissions/keeper/keeper.go
x/emissions/keeper/msgserver/msg_server_registrations.go
x/emissions/keeper/msgserver/msg_server_topics.go
x/emissions/module/rewards/rewards.go

Removes public access from outside the keeper module to internal keepers e.g. bank and auth
Makes sure when you do "find all references on one of the keepers" you don't miss references because they're wrapped around a Get function
Makes sure that every `SendCoinsFromXToY` is injectible (e.g. for logging) from within the emissions keeper
Makes sure that if we need to edit flows related to coins we can do so in one place

Limit Exposure of Internal Keepers inside Emissions Keeper

---

.github/workflows/format_and_test.yml

In #290 I made all the integration and unit tests run on the same github VM in some weird goal of either making our github actions cheaper and or faster
I am now of the conclusion that it is definitely not faster
therefore, we use job dependencies to allow parallelizing the github action on multiple VMs. I used [this](https://medium.com/tradeling/how-to-achieve-parallel-execution-using-github-actions-d534404702fb) as a reference.

Parallelize Unit and Integration Testing Jobs

---

.github/workflows/format_and_test.yml
test/invariant/invariants.patch
x/emissions/keeper/invariants.go

Check the following invariants during the course of an integration test run:
* The balance of the totalStake in the emissions keeper should always equal the cosmos-sdk /x/bank balance of the "allorastaking" bank account
* The sum of all topicStake in every topic should always equal the totalStake
* The sum of all stakeReputerAuthority for a given topic should always equal the topic stake for that topic
* The sum of all stakeReputerAuthority should equal the total stake
* The stakeSumFromDelegator should always equal the sum of `delegatedStakes[topicid, delegator, all reputers for that delegator])`
* The stakeFromDelegatorsUponReputer should always equal the sum of `delegatedStakes[topicid, all delegators for that reputer, reputer]`
* The sum of all (delegateRewardsPerShare * delegated …

 Check Invariants Hold During Integration Testing

---

test/common/node_config.go
test/integration/create_topic_test.go
test/integration/distribution_test.go
test/integration/fund_topic_test.go
test/integration/params_test.go
test/integration/registration_test.go
test/integration/staking_test.go
test/integration/update_params_test.go
test/integration/upgrade_test.go
test/integration/worker_inference_and_forecast_test.go
test/stress/create_topic_test.go
test/stress/funding_test.go
test/stress/getters_helpers_test.go
test/stress/params_test.go
test/stress/registration_test.go
test/stress/reputers_test.go
test/stress/staking_test.go
test/stress/workers_test.go

Remove global shared context from TestConfig struct
Every place in the test suite where `m.Ctx` was called, instead just call context.Background and create a new separate context object.
Not actually sure this works, just a test PR to test the idea

Functions create their own context.Ctx to call cosmosclient.Client

---

app/topics_handler.go
x/emissions/keeper/inference_synthesis/nonce_mgmt.go
x/emissions/keeper/inference_synthesis/nonce_mgmt_test.go
x/emissions/module/abci.go

Closes: #XXX
* Defines worker nonce as blockHeight, instead of blockheight + epochLength. Meaning is changed from "the block for when the inference should be made" to "the block when the request is made".
* In places where this is used, adjust adding epochLength where appropriate
* Use last reputer commit nonce as previousLosses value where applicable. Keep previous value (`reputerNonce - epochLength`) on first commit and as default if no losses are found.
*(example:)*
- *Modifies the topNonces tests that are failing due to the changes*
- [ X ] N/A
Will be documented as part of a larger change on nonces management.

EpochLength changes + Using last commit at request time

---

app/topics_handler.go
x/emissions/keeper/keeper.go
x/emissions/keeper/msgserver/msg_server_losses.go
x/emissions/keeper/msgserver/msg_server_losses_test.go

Closes: #XXX
Uses ReputerRequestNonce.ReputerNonce instead of ReputerRequestNonce.WorkerNonce.
This change modifies tests. Some are removed because they no longer make sense or fail differently.
- [ X] N/A
Documented rework needed on Nonces on Allora documentaiton site. Part of its parent ticket.

Adjustments on WorkerNonces - Use ReputerNonce

---

x/emissions/module/abci.go

Closes: #XXX
Change the pruning accordingly to using one less epochLength.
This change is a trivial change without any test coverage.
- [ X ] N/A

Allow one extra epochLength on the pruning

---

x/emissions/keeper/msgserver/msg_server_stake.go
x/emissions/keeper/msgserver/msg_server_stake_test.go

This PR fixes a critical-severity issue that would allow any random person on the internet to denial of service the Allora chain, by sending a negative Coin amount to the RemoveDelegateStake function. The fix merely checks that the value is positive, thereby preventing an eventual panic and halt of the chain.
This change added tests that check that you cannot try to RemoveStake of negative amounts of coins.
This PR has no implications on documentation.

Prevent calling RemoveStake/RemoveDelegateStake with negative amount

---

app/topics_handler.go
x/emissions/module/abci.go

This PR closes a subtle race condition bug that could potentially happen anywhere that for-loops are spawned with `go func` - the for loop operates on a reference which changes faster than the function call can potentially happen, causing a function to use the wrong parameter when referenced.
The solution is very simple, make a local copy of the variable and pass the resulting function by copy, rather than by reference - then there's no way the for loop can accidentally reference the wrong data. 
This change is hard to test, so we're not going to write a unit test to simulate it explicitly. The performance implicaitons of doing a pass-by-copy are trivial, therefore there is no reason to not do the safer thing. Our existing test suite should test that the change does not have correctness …

Prevent potential race condition by making parallelized pass-by-copy rather than reference

---

x/emissions/keeper/invariants.go
x/emissions/keeper/keeper.go

The collections.go cosmos-sdk library provides a manual iteration function for iterating over all the keys of a collection. However the iterator must be manually closed by the caller. 
I suspect this probably would cause memory leaks if we didn't fix this issue, but deferring an iter.Close() call is trivial so we fix it here
In terms of the existing code functionality, this change is covered by our existing unit and integration tests.
This PR has no implications for our documentation

Collections.go Iterators need to be manually closed

---

test/invariant/invariants.patch
x/emissions/module/abci.go
x/emissions/module/rewards/topic_rewards.go

This change simplifies a hard-to-read and hard-to-reason about piece of code that parallelized the picking of churn ready topics from the active set. After this PR the code is easier to read and understand, and has less likelihood of causing non-determinism issues. The tradeoff is that the code may run slightly slower in serial.
This change is not trivial, however it is a small diff / refactor PR and our existing test cases should be able to cover the change.
This PR does not have any implications for documentation.

Remove `go func` parallelization in ABCI EndBlocker

---

x/emissions/keeper/msgserver/msg_server_worker_payload.go
x/emissions/keeper/msgserver/msg_server_worker_payload_test.go
x/mint/keeper/keeper.go

Fixed `InsertBulkWorkerPayload` accepting duplicated forecast elements.
UPDATE:
Also adding a fix of a compilation error changing the name of a variable related the total number of tokens minted
Ticket: https://linear.app/upshot/issue/ORA-1862/compilation-error-due-to-using-resesrved-word-as-a-name
*(or)*
*(or)*
*(example:)*

[ORA-1911] Removing duplicates on worker payload msg

---

x/emissions/module/stake_removals.go

The stake removals are processed in ABCI End Blocker and if there is an error sending tokens or an error writing into the keeper state, the intent is to skip that stake removal and keep going. However, if the stake removal is incorrect, it actually can enter an error state where the tokens are sent, but the state machine is not updated, causing a theft of funds.
This PR uses a cache context to try writing the state into the state machine, and, if there is an error, skip writing the state.
Our existing test cases should confirm that this change does not change the overall flow of stake removal
There is no implication on documentation from this PR.

Silent errors in Remove{Delegate}Stake flow causes incorrect states

---

x/emissions/keeper/msgserver/msg_server_demand.go
x/emissions/keeper/msgserver/msg_server_stake.go

This PR improves error handling in `FundTopic` and `RewardDelegateStake`
In the FundTopic case we return the error correctly but also return a non nil response for the RPC request, which may a) cause issues and confusion for consumers and b) prevent transactions from failing that should not be included in a block (not actually sure about this, just hypothecating)
In the case of RewardDelegateStake, we silently ignore errors allowing transactions to continue with errors, which allows Delegators to claim rewards multiple times. This is actually a serious theft-of-funds bug.
This change does not require additional test coverage.
This change does not have any documentation-related implications.

Improve Error Handling in FundTopic and RewardDelegateStake

---

x/emissions/keeper/msgserver/msg_server_topics.go
x/emissions/types/errors.go

Closes: #ORA-2037 
Prevent topics to be created with a ground truth lag too big so that the reputation nonce could be dropped when the ground truth is revealed. 
- [X ] Allora documentation site `docs.allora.network` source code at: `https://github.com/allora-network/docs` - as part of pparent ticket

Prevent too big ground truth lag

---

docker-compose.yaml
x/emissions/keeper/actor_utils/losses.go
x/emissions/module/abci.go

Fulfill reputer nonce if in error, to avoid retrying reputation unnecessarily
Error handling 
- [X ] Allora documentation site `docs.allora.network` source code at: `https://github.com/allora-network/docs` -- as part of parent ticket ORA-2015.

error handling and fulfill losses nonce on failure

---

x/emissions/types/msg_create_topic.go

This change validates additional parameters for the creation of new topics, namely it puts a limit on the size of string data like metadata, defaultArg etc
This change is a trivial rework without any additional test coverage.
no documentation implications

Sanity check create topic input sizes

---

x/emissions/module/rewards/scores.go

This PR corrects a really nasty typo bug where we were updating inference scores in a forecaster function
Our test suite should have caught this. The fact that it didn't means we need further testing. However our existing tests will at least confirm that this PR is directionally correct...
Definitely with the addition of high-precision unit tests that match what the research team's python implementations numbers are will help with this issue, that's coming in a later PR.
This is an internal change with no documentation related implications

GenerateForecastScores Should Update Forecasted Scores Not Inference Scores

---

x/mint/module/abci.go
x/mint/module/module_test.go

We calculate target emission and the emission rate on a monthly cadence. In the first month we have no previous history to use for the exponential moving average which returns e_i. Therefore, in that case, we use the target e_i instead of the exponential moving average, directly.
Our existing tests should at least cover that this does not break anything
No Documentation changes needed.

[ORA-1613] Initial Value for emission per unit staked token = target

---

x/emissions/keeper/msgserver/msg_server_topics.go
x/emissions/keeper/msgserver/msg_server_util_payment.go

We have staticcheck in CI/CD, but apparently visual studio code is using some additional linters as well because staticcheck did not catch these unused function parameters but visual studio code did.
We should at some point figure out what that tool is and use it in ci/cd. Maybe use https://github.com/golangci/golangci-lint instead of just staticcheck.
No documentation change implications

Silence unused function parameter warnings

---

x/emissions/types/errors.go
x/mint/types/errors.go

According to the Cosmos SDK [Errors documentation](https://docs.cosmos.network/main/build/building-modules/errors#registration), the error code :
Must be greater than one, as a code value of one is reserved for internal errors.
This fixes that broken rule.
No documentation changes

Do not use comos-sdk reserved error 1

---

test/invariant/invariants.patch
x/emissions/module/abci.go
x/emissions/module/rewards/topic_rewards.go

This PR is a re-implementation of #440 - at some point #458 overwrote that PR, and reverted all the changes in the PR. This PR restores that PR. The original text below, and see the original PR for some conversation on non-determinism.
This change simplifies a hard-to-read and hard-to-reason about piece of code that parallelized the picking of churn ready topics from the active set. After this PR the code is easier to read and understand, and has less likelihood of causing non-determinism issues. The tradeoff is that the code may run slightly slower in serial.
This change is not trivial, however it is a small diff / refactor PR and our existing test cases should be able to cover the change.
This PR does not have any implications for documentation.

Undo Overwrite of #440 : Remove go func parallelization in ABCI EndBlocker 

---

x/emissions/keeper/actor_utils/worker.go
x/emissions/keeper/inference_synthesis/network_inferences.go
x/emissions/keeper/msgserver/msg_server_demand.go
x/emissions/keeper/msgserver/msg_server_demand_test.go
x/emissions/keeper/msgserver/msg_server_registrations.go
x/emissions/keeper/msgserver/msg_server_registrations_test.go
x/emissions/keeper/msgserver/msg_server_reputer_payload.go
x/emissions/keeper/msgserver/msg_server_stake.go
x/emissions/keeper/msgserver/msg_server_topics.go
x/emissions/keeper/msgserver/msg_server_util_payment.go
x/emissions/keeper/msgserver/msg_server_worker_payload.go
x/emissions/keeper/queryserver/query_server_topics.go
x/emissions/keeper/topic_weight.go
x/emissions/module/rewards/topic_rewards.go

- Fix network inferences queries - adding back the fix that was overwritten by the PR #458
- Remove Stake double counting on topic weight calculation
- Remove Revenue double counting on topic weight calculation - Fix audit issue: https://github.com/sherlock-audit/2024-06-allora-judging/issues/46
- Removed unused params on `checkBalanceAndSendFee` function
*(or)*
*(or)*
This change added tests and can be verified as …

Added fixes after b7s removal PR

---

test/invariant/inferences_test.go
test/invariant/invariant_test.go
test/invariant/transitions_test.go

Makes updates to the invariant / fuzzer test suite so that inferences can actually be sent during a fuzz run
No tickets created for this one
These changes are tests themselves. They have no implications relevant to documentation

Make Invariant Fuzzer runnable against release v0.3.0

---

math/dec.go
math/dec_test.go
math/dec_test_internal.go
x/emissions/keeper/invariants.go
x/emissions/keeper/keeper.go
x/emissions/keeper/msgserver/msg_server_stake.go
x/emissions/keeper/msgserver/msg_server_stake_test.go
x/emissions/keeper/queryserver/query_server_stake.go
x/emissions/module/rewards/reputer_rewards.go
x/emissions/module/rewards/rewards.go
x/mint/keeper/emissions_test.go
x/mint/keeper/keeper.go
x/mint/keeper/query_server.go
x/mint/module/abci.go

While debugging other issues I observed a case where a conversion from alloraMath.Dec -> cosmosMath.LegacyDec caused a silently failing error. Also the conversion from alloraMath.Dec -> cosmosMath.Int is capable of panicking, which, if ever happened, could cause a chain halt.
The solution is to make these conversions throw errors instead, and then the calling code can figure out the appropriate way to deal with the error (or halt the chain in extreme cases).
This code also moves the `dec_test.go` file from package `math` (so compiled into every binary we produce) to package `math_test` (only compiled in test binaries)
https://linear.app/alloralabs/issue/PROTO-2058/sdkinttrim-and-sdklegacydec-can-panic-causing-chain-halt
These changes are covered by existing unit tests on the happy path. …

alloraMath -> cosmosMath conversions: make panicking code return errors instead

---

app/topics_handler.go
app/upgrades/v0_3_0/upgrades.go
app/upgrades/v0_4_0/upgrades.go
scripts/l1_node.sh
test/invariant/invariants.patch
x/emissions/keeper/actor_utils/util_sort.go
x/emissions/keeper/actor_utils/util_test.go
x/emissions/keeper/inference_synthesis/network_regrets.go
x/emissions/keeper/msgserver/msg_server_worker_payload.go
x/emissions/module/abci.go
x/emissions/types/events.go
x/ibc/testing/ibc_setup_test.go
x/mint/keeper/emissions_test.go

- Remove unnecessary `fmt.Print` statements
- Added telemetry + new endblock metric for emissions module

Added telemetry and removed unnecessary logs

---

CHANGELOG.md
x/emissions/keeper/msgserver/msg_server_stake_test.go
x/emissions/module/rewards/rewards.go

Add a zero-check on rewards once converted to cosmosInt.
Added two tests on rewards conversion checks.
PROTO-2244 
Define if this is the best place for those tests to exist

Add zero check on the cosmosInt + conversion tests

---

CHANGELOG.md

Our changelog is out of date on dev branch. This sets all the changes that were v0.3.0 as marked for v0.3.0 and starts a new category for v0.4.0.
Fixes a "bug" introduced in #544 where 544 was marked as a change for v0.3.0 - we should avoid making this kind of mistake in the future with more formal processes. We should also require changes to changelog for every PR, maybe enforced by linter rules on the changelog.

Bump Changelog Version

---

CHANGELOG.md
x/emissions/keeper/actor_utils/losses_test.go
x/emissions/keeper/actor_utils/worker_test.go
x/emissions/keeper/inference_synthesis/network_inference_builder_test.go
x/emissions/keeper/queryserver/query_server_forecasts_test.go
x/emissions/keeper/queryserver/query_server_inferences_test.go
x/emissions/keeper/queryserver/query_server_losses_test.go
x/emissions/keeper/queryserver/query_server_params_test.go
x/emissions/keeper/queryserver/query_server_registrations_test.go
x/emissions/keeper/queryserver/query_server_reward_test.go
x/emissions/keeper/queryserver/query_server_score_test.go
x/emissions/keeper/queryserver/query_server_stake_test.go
x/emissions/keeper/queryserver/query_server_test.go
x/emissions/keeper/queryserver/query_server_topics_test.go
x/emissions/keeper/queryserver/query_server_whitelist_test.go
x/emissions/migrations/v2/migrate_test.go
x/emissions/migrations/v3/migrate_test.go
x/emissions/module/rewards/rewards_internal_test.go
x/emissions/module/rewards/rewards_test.go
x/mint/keeper/emissions_test.go
x/mint/keeper/keeper_test.go
x/mint/keeper/msg_server_test.go

This is a refactoring PR with no state changes. It renames testify TestSuites to match with the packages they are actually testing.
These changes are tested by running them / our existing tests
This is an internal change that does not require documentation.

Refactor: Rename TestSuite names

---

x/emissions/keeper/actor_utils/losses.go
x/emissions/keeper/actor_utils/losses_test.go
x/emissions/keeper/msgserver/msg_server_worker_payload.go
x/emissions/module/rewards/rewards.go
x/emissions/module/rewards/scores.go
x/emissions/module/rewards/scores_test.go

One of the properties of the reputer bundle was not being considered in this function, causing a chain halt!

Hot fix:  Ensuring worker presence between reputer reports

---

CHANGELOG.md
x/emissions/keeper/keeper.go
x/emissions/module/abci.go
x/emissions/module/rewards/nonce_management.go
x/emissions/module/rewards/rewards_test.go
x/emissions/module/rewards/scores_test.go

Issue originally identified by @RedBird96 
Our devnet revealed the following suspicious coincidences in time of worker nonce creation and fulfillment:
and:
This was in addition to a glut logs on our workers that showed many attempts to commit data yet minimal success.
Additionally, many community members have been reporting inability to participate in testnet for quite some time.
It appears our worker nonces are sometimes being closed immediately after they're opened.
I don't understand why this is not universally the case, but my reading of the code is congruent with the observation that this is overwhelmingly the case, making it impossible to join a topic epoch unless you happen to time yourself exactly when the worker nonce is opened/closed.
Must also merge to `dev` branch.
*Fill this …

only close worker nonces after topic window submission number of blocks

---

x/emissions/keeper/inference_synthesis/network_inferences_test.go
x/emissions/keeper/inference_synthesis/network_regrets.go

These tests cover the cases where:
- all inferers are new
- all forecasters are new, and all inferers are old
- one inferer is old, and the others are new
- all inferers are old, one forecaster is old, and the other forecasters are new

Retesting edge cases with high precision for the network inferences

---

CHANGELOG.md
x/emissions/keeper/keeper.go
x/emissions/keeper/keeper_test.go
x/emissions/keeper/msgserver/msg_server_reputer_payload.go
x/emissions/keeper/msgserver/msg_server_worker_payload.go

Scores were inconsistently using current height or nonce. I modified to just use nonces.
I used this to also modify how we were checking for idempotent submissions (1 submission per actor type per topic per epoch).
This is a simpler solution than https://github.com/allora-network/allora-chain/pull/609
[From conversation](https://github.com/allora-network/allora-chain/pull/609) with @xmariachi and @guilherme-brandao 

ensure every score blockheight is built with nonce not current height

---

.gitignore
test/generate_genesis.sh
test/integration/integration_test.go
test/invariant/invariant_test.go
test/local_testnet_l1.sh
test/local_testnet_upgrade_l1.sh
test/stress/README.md
test/stress/stress_test.go

The integration tests expect a genesis generation script inside the docker container in order to run a local network simulation.
PROTO-2465
These changes are tested by our integration tests being functional. As this is an internal change, we skip updating the changelog or any documentation updates.

Add Genesis Generation script for local network and integration tests

---

CHANGELOG.md
README.md
cmd/allorad/cmd/commands.go
cmd/allorad/cmd/testnet.go

Add the `in-place-testnet` subcommand to the allorad binary which loads blockchain state data from a different environment.
PROTO-2180, PROTO-2590, PROTO-2583
Tested locally by manual process.
Init a new allorad chain instance and test key
```
allorad init devnet
allorad keys add test
```
Copy an existing node snapshot (see our internal documentation on how to do this) of `/data/*.db /data/*.wal` to localhost. Extract the folder to `~/.allorad/data`
Get the local validator key: 
`allorad comet show-address`
Start the node with an in-place-testnet, swapping the state of the node for the snapshot state
`allorad in-place-testnet devnet allovaloper<comet address> --home $HOME/.allorad --minimum-gas-prices 0uallo --skip-confirmation`
Probably should provide documentation for this process …

[PROTO-2180] Load testnet state into local fork via in-place-testnet command

---

test/testutil/testdata.go
utils/syncpool.go
utils/syncpool_test.go
x/emissions/keeper/msgserver/msg_server.go
x/emissions/types/validations.go

Reduce memory allocations and GC operations by reusing buffers from a pool when we call marshal.
Inspired by https://github.com/cosmos/cosmos-sdk/blob/ee3d320eaa55e5aab1bf216f03a8d8aa5833d549/store/v2/internal/encoding/encoding.go#L140-L141
https://linear.app/alloralabs/issue/cosm/efficient-protobuf-serialization

Use a pool to reduce allocations and GC operations on marshal calls

---

x/emissions/keeper/genesis.go
x/emissions/keeper/keeper.go

* Implement `InitGenesis` section for `RewardCurrentBlockEmission`

missing InitGenesis entry for rewardCurrentBlockEmission

---

CHANGELOG.md
utils/migutils/migutils.go
utils/migutils/migutils_test.go
x/emissions/migrations/v3/migrate.go
x/emissions/migrations/v3/migrate_test.go
x/emissions/migrations/v4/migrate.go
x/emissions/migrations/v5/migrate.go
x/emissions/migrations/v5/migrate_test.go

This is a patch, but still part of v0.6.0 release.
We were not deleting enough values in the KV store that may have been affected by initial regret poisoning. This had to be corrected or else other values would risk re-poisoning everything else within each topic.
- Re-uses existing function + unit test
- Was original intention of original author of that migration. Documented through comments.

wipe all values in v5 emissions module migration instead of just some
